select CODEMP, CODTNS, DESTNS,  LISMOD, decode(E001TNS.VENFAT,' ','N',E001TNS.VENFAT) CONTABIL,  decode(E001TNS.USU_RELVND,' ','N',E001TNS.USU_RELVND) GERENCIAL
from SAPIENS.E001TNS 
where CODEMP=25 
  and LISMOD IN ('VES','VEF','COF','COS')
  AND SITTNS='A'
  and ( (decode(E001TNS.VENFAT,' ','N',E001TNS.VENFAT)='S') OR (decode(E001TNS.USU_RELVND,' ','N',E001TNS.USU_RELVND)='S') )
  and decode(E001TNS.VENFAT,' ','N',E001TNS.VENFAT) <> decode(E001TNS.USU_RELVND,' ','N',E001TNS.USU_RELVND) 
order by codtns  ;
