select R999MDS.CODMOD, DESMOD, DATACC, CODUSU, 
       (SELECT NOMUSU FROM R999USU WHERE R999USU.CODUSU=R999MDS.CODUSU) NOMUSU, 
       (SELECT datcre from R910USU WHERE R910USU.CODENT=R999MDS.CODUSU) CADASTRO
  from R999MDS
    WHERE codmod='RFNF901.GER'
    AND DATACC>=SYSDATE-45
order by DATACC desc 
